"""add store urls to games

Revision ID: 02bf259a654d
Revises: 58333deb2bb4
Create Date: 2026-09-04 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02bf259a654d'
down_revision: Union[str, None] = '58333deb2bb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('steam_store_url', sa.String(length=1024), nullable=True))
    op.add_column('games', sa.Column('xbox_store_url', sa.String(length=1024), nullable=True))
    op.add_column('games', sa.Column('playstation_store_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'playstation_store_url')
    op.drop_column('games', 'xbox_store_url')
    op.drop_column('games', 'steam_store_url')
    # ### end Alembic commands ###
