"""add similar game igdb ids to games

Revision ID: 275a2233c4a1
Revises: 0b3eab3577e8
Create Date: 2026-06-21 13:52:42.505097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '275a2233c4a1'
down_revision: Union[str, None] = '0b3eab3577e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('similar_game_igdb_ids', sa.JSON(), nullable=True, comment="IGDB's similar_games field, cached at import/resync time — powers recommendations (M8)"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'similar_game_igdb_ids')
    # ### end Alembic commands ###
