"""initial schema

Revision ID: 49c9101ebf9c
Revises: 
Create Date: 2026-06-20 12:32:45.568136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49c9101ebf9c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('igdb_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collections'))
    )
    op.create_index(op.f('ix_collections_igdb_id'), 'collections', ['igdb_id'], unique=True)
    op.create_index(op.f('ix_collections_slug'), 'collections', ['slug'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('igdb_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_index(op.f('ix_companies_igdb_id'), 'companies', ['igdb_id'], unique=True)
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=False)
    op.create_table('franchises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('igdb_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_franchises'))
    )
    op.create_index(op.f('ix_franchises_igdb_id'), 'franchises', ['igdb_id'], unique=True)
    op.create_index(op.f('ix_franchises_slug'), 'franchises', ['slug'], unique=False)
    op.create_table('genres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('igdb_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genres'))
    )
    op.create_index(op.f('ix_genres_igdb_id'), 'genres', ['igdb_id'], unique=True)
    op.create_index(op.f('ix_genres_slug'), 'genres', ['slug'], unique=False)
    op.create_table('import_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.Enum('csv', 'json', name='importsource', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'partial', name='jobstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_history'))
    )
    op.create_table('platforms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('igdb_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('abbreviation', sa.String(length=50), nullable=True),
    sa.Column('logo_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platforms'))
    )
    op.create_index(op.f('ix_platforms_igdb_id'), 'platforms', ['igdb_id'], unique=True)
    op.create_index(op.f('ix_platforms_slug'), 'platforms', ['slug'], unique=False)
    op.create_table('regions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regions')),
    sa.UniqueConstraint('name', name=op.f('uq_regions_name'))
    )
    op.create_table('saved_filters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('filter_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_filters'))
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True, comment='hex color for UI chips'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('name', name=op.f('uq_tags_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('igdb_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('slug', sa.String(length=512), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('storyline', sa.Text(), nullable=True),
    sa.Column('igdb_url', sa.String(length=1024), nullable=True),
    sa.Column('first_release_date', sa.BigInteger(), nullable=True),
    sa.Column('cover_url', sa.String(length=1024), nullable=True),
    sa.Column('total_rating', sa.Float(), nullable=True),
    sa.Column('aggregated_rating', sa.Float(), nullable=True),
    sa.Column('category', sa.Enum('main_game', 'dlc_addon', 'expansion', 'bundle', 'standalone_expansion', 'mod', 'episode', 'season', 'remake', 'remaster', 'expanded_game', 'port', 'fork', 'pack', 'update', name='gamecategory', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('igdb_category_id', sa.Integer(), nullable=True),
    sa.Column('parent_game_id', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('igdb_updated_at', sa.BigInteger(), nullable=True, comment='IGDB updated_at watermark, used for incremental sync'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_games_collection_id_collections')),
    sa.ForeignKeyConstraint(['parent_game_id'], ['games.id'], name=op.f('fk_games_parent_game_id_games')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_games'))
    )
    op.create_index(op.f('ix_games_collection_id'), 'games', ['collection_id'], unique=False)
    op.create_index(op.f('ix_games_igdb_id'), 'games', ['igdb_id'], unique=True)
    op.create_index(op.f('ix_games_name'), 'games', ['name'], unique=False)
    op.create_index(op.f('ix_games_parent_game_id'), 'games', ['parent_game_id'], unique=False)
    op.create_index(op.f('ix_games_slug'), 'games', ['slug'], unique=False)
    op.create_table('artworks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('igdb_id', sa.BigInteger(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_artworks_game_id_games')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artworks')),
    sa.UniqueConstraint('igdb_id', name=op.f('uq_artworks_igdb_id'))
    )
    op.create_index(op.f('ix_artworks_game_id'), 'artworks', ['game_id'], unique=False)
    op.create_table('game_companies',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('developer', 'publisher', 'porting', 'supporting', name='companyrole', native_enum=False, create_constraint=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_game_companies_company_id_companies')),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_game_companies_game_id_games')),
    sa.PrimaryKeyConstraint('game_id', 'company_id', 'role', name=op.f('pk_game_companies'))
    )
    op.create_table('game_franchises',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('franchise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchises.id'], name=op.f('fk_game_franchises_franchise_id_franchises')),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_game_franchises_game_id_games')),
    sa.PrimaryKeyConstraint('game_id', 'franchise_id', name=op.f('pk_game_franchises'))
    )
    op.create_table('game_genres',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_game_genres_game_id_games')),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_game_genres_genre_id_genres')),
    sa.PrimaryKeyConstraint('game_id', 'genre_id', name=op.f('pk_game_genres'))
    )
    op.create_table('game_platforms',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_game_platforms_game_id_games')),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], name=op.f('fk_game_platforms_platform_id_platforms')),
    sa.PrimaryKeyConstraint('game_id', 'platform_id', name=op.f('pk_game_platforms'))
    )
    op.create_table('game_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('play_status', sa.Enum('none', 'backlog', 'playing', 'completed', 'abandoned', name='playstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('playtime_minutes', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.Date(), nullable=True),
    sa.Column('last_played_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_game_progress_game_id_games')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_progress'))
    )
    op.create_index(op.f('ix_game_progress_game_id'), 'game_progress', ['game_id'], unique=True)
    op.create_table('game_tags',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_game_tags_game_id_games')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_game_tags_tag_id_tags')),
    sa.PrimaryKeyConstraint('game_id', 'tag_id', name=op.f('pk_game_tags'))
    )
    op.create_table('game_videos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('igdb_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('video_id', sa.String(length=255), nullable=False, comment='YouTube video id'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_game_videos_game_id_games')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_videos')),
    sa.UniqueConstraint('igdb_id', name=op.f('uq_game_videos_igdb_id'))
    )
    op.create_index(op.f('ix_game_videos_game_id'), 'game_videos', ['game_id'], unique=False)
    op.create_table('library_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('owned', 'wishlist', name='librarystatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('format', sa.Enum('physical', 'digital', 'iso', 'rom', name='mediaformat', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('digital_storefront', sa.String(length=100), nullable=True, comment='e.g. Steam, PSN, Epic Games — only meaningful when format=digital'),
    sa.Column('edition', sa.String(length=255), nullable=True, comment='Free text for now; revisit as a structured table if IGDB editions data improves'),
    sa.Column('acquired_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_library_items_game_id_games')),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], name=op.f('fk_library_items_platform_id_platforms')),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_library_items_region_id_regions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_library_items'))
    )
    op.create_index(op.f('ix_library_items_game_id'), 'library_items', ['game_id'], unique=False)
    op.create_index(op.f('ix_library_items_status'), 'library_items', ['status'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_notes_game_id_games')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    op.create_index(op.f('ix_notes_game_id'), 'notes', ['game_id'], unique=False)
    op.create_table('play_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_play_sessions_game_id_games')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_play_sessions'))
    )
    op.create_index(op.f('ix_play_sessions_game_id'), 'play_sessions', ['game_id'], unique=False)
    op.create_table('release_dates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('igdb_id', sa.BigInteger(), nullable=True),
    sa.Column('date', sa.BigInteger(), nullable=True, comment='unix timestamp'),
    sa.Column('human', sa.String(length=100), nullable=True, comment="IGDB's human-readable date string"),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_release_dates_game_id_games')),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], name=op.f('fk_release_dates_platform_id_platforms')),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_release_dates_region_id_regions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_release_dates')),
    sa.UniqueConstraint('game_id', 'platform_id', 'region_id', name=op.f('uq_release_dates_game_id')),
    sa.UniqueConstraint('igdb_id', name=op.f('uq_release_dates_igdb_id'))
    )
    op.create_index(op.f('ix_release_dates_game_id'), 'release_dates', ['game_id'], unique=False)
    op.create_table('screenshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('igdb_id', sa.BigInteger(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_screenshots_game_id_games')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_screenshots')),
    sa.UniqueConstraint('igdb_id', name=op.f('uq_screenshots_igdb_id'))
    )
    op.create_index(op.f('ix_screenshots_game_id'), 'screenshots', ['game_id'], unique=False)
    op.create_table('sync_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trigger', sa.Enum('manual', 'automatic', name='synctrigger', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('scope', sa.Enum('full', 'incremental', 'single_game', name='syncscope', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'partial', name='jobstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_sync_history_game_id_games')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_history'))
    )
    op.create_index(op.f('ix_sync_history_game_id'), 'sync_history', ['game_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_history_game_id'), table_name='sync_history')
    op.drop_table('sync_history')
    op.drop_index(op.f('ix_screenshots_game_id'), table_name='screenshots')
    op.drop_table('screenshots')
    op.drop_index(op.f('ix_release_dates_game_id'), table_name='release_dates')
    op.drop_table('release_dates')
    op.drop_index(op.f('ix_play_sessions_game_id'), table_name='play_sessions')
    op.drop_table('play_sessions')
    op.drop_index(op.f('ix_notes_game_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_library_items_status'), table_name='library_items')
    op.drop_index(op.f('ix_library_items_game_id'), table_name='library_items')
    op.drop_table('library_items')
    op.drop_index(op.f('ix_game_videos_game_id'), table_name='game_videos')
    op.drop_table('game_videos')
    op.drop_table('game_tags')
    op.drop_index(op.f('ix_game_progress_game_id'), table_name='game_progress')
    op.drop_table('game_progress')
    op.drop_table('game_platforms')
    op.drop_table('game_genres')
    op.drop_table('game_franchises')
    op.drop_table('game_companies')
    op.drop_index(op.f('ix_artworks_game_id'), table_name='artworks')
    op.drop_table('artworks')
    op.drop_index(op.f('ix_games_slug'), table_name='games')
    op.drop_index(op.f('ix_games_parent_game_id'), table_name='games')
    op.drop_index(op.f('ix_games_name'), table_name='games')
    op.drop_index(op.f('ix_games_igdb_id'), table_name='games')
    op.drop_index(op.f('ix_games_collection_id'), table_name='games')
    op.drop_table('games')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('saved_filters')
    op.drop_table('regions')
    op.drop_index(op.f('ix_platforms_slug'), table_name='platforms')
    op.drop_index(op.f('ix_platforms_igdb_id'), table_name='platforms')
    op.drop_table('platforms')
    op.drop_table('import_history')
    op.drop_index(op.f('ix_genres_slug'), table_name='genres')
    op.drop_index(op.f('ix_genres_igdb_id'), table_name='genres')
    op.drop_table('genres')
    op.drop_index(op.f('ix_franchises_slug'), table_name='franchises')
    op.drop_index(op.f('ix_franchises_igdb_id'), table_name='franchises')
    op.drop_table('franchises')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_index(op.f('ix_companies_igdb_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_collections_slug'), table_name='collections')
    op.drop_index(op.f('ix_collections_igdb_id'), table_name='collections')
    op.drop_table('collections')
    # ### end Alembic commands ###
