"""add hardware tables

Revision ID: 4c0dbd90bf0b
Revises: 551b31c9a576
Create Date: 2026-06-26 11:45:17.422445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c0dbd90bf0b'
down_revision: Union[str, None] = '551b31c9a576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accessory_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accessory_types')),
    sa.UniqueConstraint('name', name=op.f('uq_accessory_types_name'))
    )
    op.create_table('colors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_colors')),
    sa.UniqueConstraint('name', name=op.f('uq_colors_name'))
    )
    op.create_table('hardware_platforms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hardware_platforms')),
    sa.UniqueConstraint('name', name=op.f('uq_hardware_platforms_name'))
    )
    op.create_table('hardware_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hardware_types')),
    sa.UniqueConstraint('name', name=op.f('uq_hardware_types_name'))
    )
    op.create_table('manufacturers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manufacturers')),
    sa.UniqueConstraint('name', name=op.f('uq_manufacturers_name'))
    )
    op.create_table('storage_variants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_storage_variants')),
    sa.UniqueConstraint('name', name=op.f('uq_storage_variants_name'))
    )
    op.create_table('accessories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('accessory_type_id', sa.Integer(), nullable=False),
    sa.Column('official_name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('discontinued_date', sa.Date(), nullable=True),
    sa.Column('msrp', sa.Float(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('color_id', sa.Integer(), nullable=True),
    sa.Column('wireless', sa.Boolean(), nullable=False),
    sa.Column('bluetooth', sa.Boolean(), nullable=False),
    sa.Column('usb', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('external_source', sa.String(length=100), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['accessory_type_id'], ['accessory_types.id'], name=op.f('fk_accessories_accessory_type_id_accessory_types')),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], name=op.f('fk_accessories_color_id_colors')),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], name=op.f('fk_accessories_manufacturer_id_manufacturers')),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_accessories_region_id_regions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accessories')),
    sa.UniqueConstraint('external_source', 'external_id', name='uq_accessories_external_ref'),
    sa.UniqueConstraint('uuid', name=op.f('uq_accessories_uuid'))
    )
    op.create_index(op.f('ix_accessories_accessory_type_id'), 'accessories', ['accessory_type_id'], unique=False)
    op.create_index(op.f('ix_accessories_external_id'), 'accessories', ['external_id'], unique=False)
    op.create_index(op.f('ix_accessories_external_source'), 'accessories', ['external_source'], unique=False)
    op.create_index(op.f('ix_accessories_manufacturer_id'), 'accessories', ['manufacturer_id'], unique=False)
    op.create_index(op.f('ix_accessories_official_name'), 'accessories', ['official_name'], unique=False)
    op.create_table('hardware',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('hardware_platform_id', sa.Integer(), nullable=True),
    sa.Column('hardware_type_id', sa.Integer(), nullable=False),
    sa.Column('official_name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('revision', sa.String(length=100), nullable=True),
    sa.Column('generation', sa.String(length=50), nullable=True, comment="Free text, e.g. '9th' — not normalized"),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('discontinued_date', sa.Date(), nullable=True),
    sa.Column('msrp', sa.Float(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('storage_variant_id', sa.Integer(), nullable=True),
    sa.Column('color_id', sa.Integer(), nullable=True),
    sa.Column('wireless', sa.Boolean(), nullable=False),
    sa.Column('bluetooth', sa.Boolean(), nullable=False),
    sa.Column('usb', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('external_source', sa.String(length=100), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], name=op.f('fk_hardware_color_id_colors')),
    sa.ForeignKeyConstraint(['hardware_platform_id'], ['hardware_platforms.id'], name=op.f('fk_hardware_hardware_platform_id_hardware_platforms')),
    sa.ForeignKeyConstraint(['hardware_type_id'], ['hardware_types.id'], name=op.f('fk_hardware_hardware_type_id_hardware_types')),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], name=op.f('fk_hardware_manufacturer_id_manufacturers')),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_hardware_region_id_regions')),
    sa.ForeignKeyConstraint(['storage_variant_id'], ['storage_variants.id'], name=op.f('fk_hardware_storage_variant_id_storage_variants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hardware')),
    sa.UniqueConstraint('external_source', 'external_id', name='uq_hardware_external_ref'),
    sa.UniqueConstraint('uuid', name=op.f('uq_hardware_uuid'))
    )
    op.create_index(op.f('ix_hardware_external_id'), 'hardware', ['external_id'], unique=False)
    op.create_index(op.f('ix_hardware_external_source'), 'hardware', ['external_source'], unique=False)
    op.create_index(op.f('ix_hardware_hardware_platform_id'), 'hardware', ['hardware_platform_id'], unique=False)
    op.create_index(op.f('ix_hardware_hardware_type_id'), 'hardware', ['hardware_type_id'], unique=False)
    op.create_index(op.f('ix_hardware_manufacturer_id'), 'hardware', ['manufacturer_id'], unique=False)
    op.create_index(op.f('ix_hardware_official_name'), 'hardware', ['official_name'], unique=False)
    op.create_index(op.f('ix_hardware_region_id'), 'hardware', ['region_id'], unique=False)
    op.create_table('accessory_compatibility',
    sa.Column('accessory_id', sa.Integer(), nullable=False),
    sa.Column('hardware_platform_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accessory_id'], ['accessories.id'], name=op.f('fk_accessory_compatibility_accessory_id_accessories')),
    sa.ForeignKeyConstraint(['hardware_platform_id'], ['hardware_platforms.id'], name=op.f('fk_accessory_compatibility_hardware_platform_id_hardware_platforms')),
    sa.PrimaryKeyConstraint('accessory_id', 'hardware_platform_id', name=op.f('pk_accessory_compatibility'))
    )
    op.create_table('hardware_editions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hardware_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('edition_type', sa.Enum('standard', 'limited', 'special', 'bundle', name='hardwareeditiontype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('artwork_url', sa.String(length=1024), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hardware_id'], ['hardware.id'], name=op.f('fk_hardware_editions_hardware_id_hardware')),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_hardware_editions_region_id_regions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hardware_editions'))
    )
    op.create_index(op.f('ix_hardware_editions_hardware_id'), 'hardware_editions', ['hardware_id'], unique=False)
    op.create_table('user_accessories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('accessory_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('owned', 'wishlist', name='librarystatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('condition', sa.Enum('sealed', 'new', 'like_new', 'good', 'fair', 'poor', name='hardwarecondition', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('boxed', sa.Boolean(), nullable=False),
    sa.Column('complete_in_box', sa.Boolean(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['accessory_id'], ['accessories.id'], name=op.f('fk_user_accessories_accessory_id_accessories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_accessories'))
    )
    op.create_index(op.f('ix_user_accessories_accessory_id'), 'user_accessories', ['accessory_id'], unique=False)
    op.create_index(op.f('ix_user_accessories_status'), 'user_accessories', ['status'], unique=False)
    op.create_table('user_hardware',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hardware_id', sa.Integer(), nullable=False),
    sa.Column('hardware_edition_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('owned', 'wishlist', name='librarystatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('condition', sa.Enum('sealed', 'new', 'like_new', 'good', 'fair', 'poor', name='hardwarecondition', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('boxed', sa.Boolean(), nullable=False),
    sa.Column('complete_in_box', sa.Boolean(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hardware_edition_id'], ['hardware_editions.id'], name=op.f('fk_user_hardware_hardware_edition_id_hardware_editions')),
    sa.ForeignKeyConstraint(['hardware_id'], ['hardware.id'], name=op.f('fk_user_hardware_hardware_id_hardware')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_hardware'))
    )
    op.create_index(op.f('ix_user_hardware_hardware_edition_id'), 'user_hardware', ['hardware_edition_id'], unique=False)
    op.create_index(op.f('ix_user_hardware_hardware_id'), 'user_hardware', ['hardware_id'], unique=False)
    op.create_index(op.f('ix_user_hardware_status'), 'user_hardware', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_hardware_status'), table_name='user_hardware')
    op.drop_index(op.f('ix_user_hardware_hardware_id'), table_name='user_hardware')
    op.drop_index(op.f('ix_user_hardware_hardware_edition_id'), table_name='user_hardware')
    op.drop_table('user_hardware')
    op.drop_index(op.f('ix_user_accessories_status'), table_name='user_accessories')
    op.drop_index(op.f('ix_user_accessories_accessory_id'), table_name='user_accessories')
    op.drop_table('user_accessories')
    op.drop_index(op.f('ix_hardware_editions_hardware_id'), table_name='hardware_editions')
    op.drop_table('hardware_editions')
    op.drop_table('accessory_compatibility')
    op.drop_index(op.f('ix_hardware_region_id'), table_name='hardware')
    op.drop_index(op.f('ix_hardware_official_name'), table_name='hardware')
    op.drop_index(op.f('ix_hardware_manufacturer_id'), table_name='hardware')
    op.drop_index(op.f('ix_hardware_hardware_type_id'), table_name='hardware')
    op.drop_index(op.f('ix_hardware_hardware_platform_id'), table_name='hardware')
    op.drop_index(op.f('ix_hardware_external_source'), table_name='hardware')
    op.drop_index(op.f('ix_hardware_external_id'), table_name='hardware')
    op.drop_table('hardware')
    op.drop_index(op.f('ix_accessories_official_name'), table_name='accessories')
    op.drop_index(op.f('ix_accessories_manufacturer_id'), table_name='accessories')
    op.drop_index(op.f('ix_accessories_external_source'), table_name='accessories')
    op.drop_index(op.f('ix_accessories_external_id'), table_name='accessories')
    op.drop_index(op.f('ix_accessories_accessory_type_id'), table_name='accessories')
    op.drop_table('accessories')
    op.drop_table('storage_variants')
    op.drop_table('manufacturers')
    op.drop_table('hardware_types')
    op.drop_table('hardware_platforms')
    op.drop_table('colors')
    op.drop_table('accessory_types')
    # ### end Alembic commands ###
