"""add nintendo/epic/gog store urls to games

Revision ID: 5c9c931a3e64
Revises: db0fb04318f0
Create Date: 2026-09-05 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c9c931a3e64'
down_revision: Union[str, None] = 'db0fb04318f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('nintendo_store_url', sa.String(length=1024), nullable=True))
    op.add_column('games', sa.Column('epic_games_store_url', sa.String(length=1024), nullable=True))
    op.add_column('games', sa.Column('gog_store_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'gog_store_url')
    op.drop_column('games', 'epic_games_store_url')
    op.drop_column('games', 'nintendo_store_url')
    # ### end Alembic commands ###
