"""add accessory hardware links

Revision ID: 674b1d15c69f
Revises: 4c0dbd90bf0b
Create Date: 2026-06-26 21:02:09.520913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '674b1d15c69f'
down_revision: Union[str, None] = '4c0dbd90bf0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accessory_hardware_links',
    sa.Column('accessory_id', sa.Integer(), nullable=False),
    sa.Column('hardware_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accessory_id'], ['accessories.id'], name=op.f('fk_accessory_hardware_links_accessory_id_accessories')),
    sa.ForeignKeyConstraint(['hardware_id'], ['hardware.id'], name=op.f('fk_accessory_hardware_links_hardware_id_hardware')),
    sa.PrimaryKeyConstraint('accessory_id', 'hardware_id', name=op.f('pk_accessory_hardware_links'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accessory_hardware_links')
    # ### end Alembic commands ###
