"""add edition to accessories

Revision ID: fcde87082b21
Revises: 674b1d15c69f
Create Date: 2026-06-27 00:10:06.736324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcde87082b21'
down_revision: Union[str, None] = '674b1d15c69f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accessories', sa.Column('edition', sa.String(length=255), nullable=True, comment="Free text, e.g. 'Spider-Man 2 Limited Edition'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accessories', 'edition')
    # ### end Alembic commands ###
